### PR TITLE
autotest-server-tests: update path for multi_host migration

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1394608

**Comment by XueqiangWei** [comment]
@lmr  the travis-ci error, the command "sudo apt-get -y --force-yes install autotest" failed and exited with 100 during . I think file ".travis.yml" should be updated, could you please help solve this issue? thank you.

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by XueqiangWei** [comment]
@xutian as we talked, already updated. Please help review, thank you.

**Comment by aliang123** [comment]
Check again, looks ok.
Acked-by: Aihua Liang<aliang@redhat.com>

**Comment by xutian** [comment]
looks good to me,

**Pull request merged**
